apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-8cix
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-8cix
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-8cix
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-8cix
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-8cix
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zwzj-tenant/quarkus/devfile-sample-code-with-quarkus-8cix@sha256:b5e53edd2eb94e806bfa7e25a143badb559614606b00bfea2ab1a79a60ef920f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
